bot:
  token: ""
  owner_id: 269758783557730314

emojis:
  angry: ğŸ˜¡
  crying: ğŸ˜­
  dead: ğŸ’€
  facepalm: ğŸ¤¦
  middle_finger: ğŸ–•
  laser_eyes: ğŸ˜ˆ
  love: â¤ï¸
  peace: âœŒï¸
  peeking: ğŸ‘€
  smiling: ğŸ™‚
  sunglasses: ğŸ˜
  thinking: ğŸ¤”
  waving: ğŸ‘‹
  weary: ğŸ˜©
  wink: ğŸ˜‰